### ISSUE TITLE
Numbers in Figure 5?

### ISSUE THREAD

**Issue by zihaohe123** [chan0park/NormVio#2]
Hi Chan! I'm interested in this paper. Could you provide the exact numbers of Figure 5 in the paper? Thanks a lot!

**Comment by chan0park** [comment]
Hi @zihaohe123, I updated a [file](https://drive.google.com/file/d/1WJg5F8E8osRpkmkqyqcnKlO4voz6tBuQ/view) that contains the exact number illustrated in Figure 5 to the released google drive folder. Let me know if you have any further questions.
