### ISSUE TITLE
What is the period of your dataset?

### ISSUE THREAD

**Issue by ChenK7166** [chan0park/NormVio#3]
Hello, I am trying to retrieve your dataset into the entire discussion (not only the conversation/ thread). However, I only can match a small part of your dataset using the dataset in April 2021 from PushShift. What is the period of your dataset? Thank you!

**Comment by chan0park** [comment]
Hi, can you clarify what you meant by _the entire discussion_? Do you mean you want to reconstruct all the comments left on the each submission? And the dataset was collected in April 2021. Let me know if you have any further questions!
