### ISSUE TITLE
exact numbers in Figure 5

### ISSUE THREAD

**Issue by zihaohe123** [chan0park/NormVio#4]
Hi Chan,

I'm very interested in this paper. Could you publish the exact numbers in Figure 5 of the paper? Thanks a lot!

Best,
Zihao

**Comment by chan0park** [comment]
Hi! Please refer to #2 where I attached a file that contains numbers for Figure 5. Let me know if you need anything else.

**Comment by zihaohe123** [comment]
Thank you Chan! I even forgot that I already asked this question in March. 
Sorry for this duplicate question!
